- id: arrive_dark_alarmed_id
  alias: Turn on light when Magnus or Kate arrive when dark and alarm is set
  trigger:
  - platform: state
    entity_id: device_tracker.5848228be7de
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.7c019155dd92
    from: 'not_home'
    to: 'home'
  condition:
  - condition: state
    entity_id: sensor.sector_alarm
    state: 'armed_away'
  - condition: sun
    after: sunset
    after_offset: '-2:00:00'
  action:
  - service: switch.turn_on
    entity_id: switch.tvattstuga  
- id: armed_alarm_id
  alias: Arming switch off lights and hvac
  trigger:
  - platform: state
    entity_id: sensor.sector_alarm
    from: 'disarmed'
    to: 'armed_away'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: group.lights_downstairs
  - service: switch.turn_off
    entity_id: group.lights_upstairs
  - service: switch.turn_on
    entity_id: switch.ftx__lag_drift
- id: disarmed_alarm_id
  alias: Disarming turn hvac away mode off
  trigger:
  - platform: state
    entity_id: sensor.sector_alarm
    from: 'armed_away'
    to: 'disarmed'
  condition: []
  action:
  - service: switch.turn_off
    entity_id: switch.ftx__lag_drift
