homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret gps_lat
  longitude: !secret gps_lng
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 345
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Stockholm
  # Customization file
  customize: !include customize.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218

weblink:
  entities:
    - name: 'DIR-655'
      icon: mdi:router-wireless
      url: !secret dir655_url

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

#Enable KNX component
knx:

#climate:
#  - platform: knx
#    name: "Kök vardagsrum"
#    temperature_address: '0/0/2'

sensor: !include_dir_merge_list sensors/

#ios stuff
ios:

# Text to speech
tts:
  - platform: google

# Cloud - currently only for US
#cloud:

#media_player Sony:
#  - platform: braviatv
#    host: 192.168.0.103

media_player KodiOnSony:
  - platform: kodi
    host: 192.168.0.103

device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.0.0/24
      
sector_alarm:
  email: !secret sectoralarm_email
  password: !secret sectoralarm_pwd
  alarm_id: !secret sectoralarm_alrm
  code: !secret sectoralarm_code
  thermometers: false
  alarm_panel: true

volvooncall:
  username: !secret volvo_usr
  password: !secret volvo_pwd
  scandinavian_miles: yes

tellduslive:
  
switch: !include_dir_merge_list switches/
light: !include_dir_merge_list lights/
group: !include_dir_merge_named groups/
#automation: !include_dir_merge_list automations/
automation: !include automations.yaml
script: !include scripts.yaml
